# メッセージのフォーマット（カラーコード対応）
message_format: "&c[警告] &e{player} &cがサーバーに参加できませんでした: {reason}"

# コマンド関連メッセージ
messages:
  reload_success: "&a設定をリロードしました。"
  invalid_command: "&c無効なコマンドです。/joinfailnotifier help を使用してください。"
  help_message: "&eUsage: /joinfailnotifier <reload/help>"